spring:
  thymeleaf:
    mode: HTML5
logging:
  level:
    org:
      springframework: error
server:
  port: ${port:8888}

# 记得替换成你的id和secret
wechat:
  appid: appId
  secret: secret

# h2
db:
  url: jdbc:h2:~/jiuask
  username: sa
  password: sa
  driver: org.h2.Driver